# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(null=True, verbose_name='Data')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drainarea', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICDR.Coordinate')),
            ],
        ),
        migrations.AddField(
            model_name='dataserie',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICDR.Station'),
        ),
    ]
